import blockContent from './BLOG/blockContent'
import category from './BLOG/category'
import post from './BLOG/post'
import author from './BLOG/author'
import tag from './BLOG/tag'
// import service from './SERVICES/service'
import social from './BLOG/social'
import postTags from './BLOG/postTags'
// import serviceDetails from './SERVICES/ServiceDetails/serviceDetails'
import blogDetails from './BLOG/blogDetails'
// import slider from './HOME/slider'
// import sliderInfo from './HOME/sliderInfo'
// import navbar from "./HOME/navbar"
// import homeAbout from './HOME/homeAbout' 
// import skillTitle from "./HOME/skillTitle"
// import workFlow from "./HOME/workFlow"
// import countUp from './HOME/countUp'
// import aboutHistory from './ABOUT/aboutHistory'
// import aboutusIntro from './ABOUT/aboutusIntro'
// import aboutusMission from './ABOUT/aboutusMission'
// import aboutusVideo from './ABOUT/aboutusVideo'
// import infoMedias from './CONTACT/infoMedias'
// import infoTimes from './CONTACT/infoTimes'
// import mapCoordinate from './CONTACT/mapCoordinate'
// import contactMap from './CONTACT/contactMap'
// import contactInfo from './CONTACT/contactInfo'
// import attributes from './HOME/attributes'
// import imageArray from './HOME/imageArray'
// import serviceUs from './SERVICES/serviceUs'
// import serviceUsContent from './SERVICES/serviceUsContent'
// import serviceHeader from './SERVICES/serviceHeader'
import blogHeader from './BLOG/blogHeader'
import contactHeader from './CONTACT/contactHeader'
// import aboutusHeader from './ABOUT/aboutusHeader'
// import mapLocations from './CONTACT/mapLocations'
// import ria from './ABOUT/ria'
import video from './BLOG/video'
// import project from './PROJECT/project'
import project from '@/schemas/New/project'
// import bg from './ABOUT/bg'
// import partners from './HOME/partners'
// import mystory from './HOME/mystory'
// import achievements from './HOME/achievements'
// import atest from './HOME/atest'
// import testimonials from './HOME/testimonials'
// import work from './HOME/work'
// import mission from './HOME/mission'
// import howto from './HOME/howto'
// import support from './HOME/support'
// import ourwork from './HOME/ourwork'
import home from './New/home'
import aboutIntro from './New/aboutIntro'
import achievements from './New/achievements'
import point from './New/point'
import mystory from './New/mystory'
import story from './New/story'
import skills from './New/skills'
import experience from './New/experience'
import education from './New/education'
import credentials from './New/credentials'

import myservices from './New/myservices'
import serviceTitle from './New/serviceTitle'
import serviceInfo from './New/serviceInfo'
import bioArray from './New/bioArray'
import navbar from './New/navbar'
import contactInfo from './New/contactInfo'
import infoTimes from './New/infoTimes'
import imageArray from './New/imageArray'
import serviceHeader from './New/serviceHeader'
import myCodeFields from './New/myCodeFields'
import comment from './New/comment'

export const schemaTypes = [comment, myCodeFields, imageArray, infoTimes, contactInfo, navbar, serviceHeader, bioArray, myservices, serviceTitle, serviceInfo, skills, experience, education, credentials, point, story, mystory, achievements, aboutIntro, home, project, video, contactHeader, blogHeader, post, author, category, tag, blockContent, social, postTags, blogDetails]
